stages:
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: repo/app:v1
      pushRemote: true
      registry: 127.0.0.1:34005
    env:
      PLUGIN_INSECURE: "true"
notification: {}
