stages:
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: repo/app:v1
      pushRemote: true
      registry: hub.docker.com
    env:
      PLUGIN_INSECURE: "true"
notification: {}
